export const itemList = [
  {
    searchTerm: 'Coca-Cola Cans, 12 Fl Oz, 35 Pack',
    itemName: '4900005846',
    quantity: 1,
    isCase: true,
  },
  {
    searchTerm: 'Coca-Cola Mexico Glass Bottles, 355 ML, 6 Pack, 4 Sets',
    itemName: '4900004422',
    quantity: 1,
    isCase: true,
  },
  // {
  //   searchTerm: 'spinach wraps',
  //   itemName: '7934122334',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: "French's - Yellow Mustard - 105 Oz",
  //   itemName: '4150081938',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'tomato purée',
  //   itemName: '76069500166',
  //   quantity: 1,
  //   isCase: false,
  // },
  // {
  //   searchTerm: 'crumbled feta cheese',
  //   itemName: '60688610845',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'red cabbage',
  //   itemName: '30223021261',
  //   quantity: 2,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'Cleaned Spinach - 2.5 Lbs',
  //   itemName: '3022301455',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'dill',
  //   itemName: '2060042508',
  //   quantity: 1,
  //   isCase: false,
  // },
  // {
  //   searchTerm: 'tofu',
  //   itemName: '75321474134',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'Tomatoes, 5x6 (Extra Large) - 25 Lbs',
  //   itemName: '2060042760',
  //   quantity: 3,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'cucumber',
  //   itemName: '2060035413',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'mayo',
  //   itemName: '76069500351',
  //   quantity: 2,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'ground lamb',
  //   itemName: '20713500000',
  //   quantity: 1,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'romaine lettuce',
  //   itemName: '2060042530',
  //   quantity: 4,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'Boneless, Skinless Chicken Thighs, Halal',
  //   itemName: '20795020000',
  //   quantity: 6,
  //   isCase: true,
  // },
  // {
  //   searchTerm: 'halal chuck roll',
  //   itemName: '20796680000',
  //   quantity: 6,
  //   isCase: false,
  // },
  // {
  //   searchTerm: 'O-Cedar Quick-Way Plastic Mopstick W/Blue Cut-End Mop',
  //   itemName: '7262706555',
  //   quantity: 1,
  //   isCase: false,
  // },
];
